services:
  gdsapp:
    image: starbender.fprimesharp/gdsapp:latest
    container_name: gdsapp
    build:
      context: ../../
      dockerfile: Starbender.FPrimeSharp.GdsApp/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__HealthCheckUrl=http://gdsapp:8080/health-status
      - ConnectionStrings__Default=DataSource=/data/GdsApp.db
    ports:
      - "44301:8081"
    depends_on:
      sqlite:
        condition: service_healthy
    restart: on-failure    
    volumes:
      - sqlite_data:/data
      - ./certs:/app/certs
    networks:
      - abp-network  
  
  db-migrator:
    image: starbender.fprimesharp/gdsapp:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: Starbender.FPrimeSharp.GdsApp/Dockerfile.local
    environment:
      - ConnectionStrings__Default=DataSource=/data/GdsApp.db
    command:
      - --migrate-database
    depends_on:
      sqlite:
        condition: service_healthy
    volumes:
      - sqlite_data:/data
    networks:
      - abp-network
  sqlite:
    container_name: sqlite-container
    image: alpine:latest
    command: sh -c "apk add sqlite && touch /data/GdsApp.db && sqlite3 /data/GdsApp.db '.databases' && tail -f /dev/null"
    environment:
      - TZ=UTC
    volumes:
      - sqlite_data:/data
    networks:
      - abp-network
    healthcheck:
      test: ["CMD-SHELL", "if [ -f /data/GdsApp.db ]; then exit 0; else exit 1; fi"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  sqlite_data:
    name: gdsapp_sqlite_data
networks:
  abp-network:
    name: gdsapp-network
    driver: bridge